stages:
  - build
  - staging
  - production

build:
  stage: build
  image: node:latest
  script:
    - npm
  cache:
    paths:
      - node_modules/
  only:
    - develop
    - master

staging:
  stage: staging
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=beta-app-sportsman --api-key=$HEROKU_API_KEY_SPORTSMAN
  only:
    - develop

production:
  stage: production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=app-sportsman --api-key=$HEROKU_API_KEY_SPORTSMAN
  only:
    - master
